### ISSUE TITLE
365Trac Isolation Findings

### ISSUE THREAD

**Issue by sdoniparti** [robomike/365Trac_Public#6]
(iPhone x, v13.1)
1. Uninstall the app
2. Restart the mobile
3. Go to TestFlight and Install it again
4. Allow While Using App
5. Notifications -> Allow
6. Login with Credentials
7. Looping is continuing

(iPhone x, v13.4)-Updated
1. Uninstall the app
2. Restart the mobile
3. Go to TestFlight and Install it again
4. Allow While Using App
5. Notifications -> Allow
6. Login with Credentials
7. Looping is continuing

(OnePlus 5T, Android 9)
1. Uninstall the app
2. Restart the mobile
3. Go to TestFlight and Install it again
4. Allow While Using App
5. Login with Credentials
6. Looping is continuing

(OnePlus 7T, Android 10)
1. Uninstall the app
2. Restart the mobile
3. Go to TestFlight and Install it again
4. Allow While Using App
5. Login with Credentials
6. Looping is continuing

**Comment by robomike** [comment]
This is due to slow server connection.  The home screen makes api calls to the 355Trac server.  There should be a time out error if you wait long enough,  10 seconds.
